ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "attachmentUrl"  TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "attachmentName" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "attachmentSize" INTEGER;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "attachmentType" TEXT;
ALTER TABLE "Message" ALTER COLUMN "content" SET DEFAULT '';
